# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d193163a9e1806697efbd67b1f42883ffb435bd75ead5a846aa917ed355e4bd4812464d83b752df7032db6d5c85024eca37daa185efe676ef7a442993acca037

test:
  secret_key_base: 641320f40a1851e04b847e4ee51164e1c16fbecab92d9033fe494eb554bae6a753bd8b7052b679a3321e9987bb2de454aad79bcfce0b5d269ff1c5d6c33cf0dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
